# Generated by Django 3.2.9 on 2022-01-30 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_patient_profile_verify'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient_profile',
            name='verify',
        ),
    ]
