# Generated by Django 3.2.9 on 2022-01-30 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_remove_patient_profile_verify'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_profile',
            name='email',
            field=models.EmailField(blank=True, max_length=50),
        ),
    ]
