# Generated by Django 3.2.9 on 2022-01-30 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_auto_20220130_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor_profile',
            name='email',
            field=models.EmailField(blank=True, max_length=50),
        ),
    ]
