# Generated by Django 3.2.9 on 2022-01-30 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_doctor_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor_profile',
            name='email',
            field=models.EmailField(max_length=50),
        ),
    ]
